export default {
  description: "Karty tarota z podstawowymi informacjami",
  cards: [
    {
      name: "Głupiec",
      number: "0",
      omen: "zły",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/glupiec.jpg",
      fortune_telling: [
        "Wypatruj nowych projektów i nowych początków",
        "Przygotuj się na test Twojej wiary",
        "Coś nowego pojawi się na twojej drodze, bądź gotowy",
      ],
      keywords: ["wolność", "wiara", "brak doświadczenia", "niewinność"],
      meanings: {
        light: [
          "Uwolnienie się od ograniczeń",
          "Wyrażanie radośćci i młodzieńczy wigor",
          "Bycie otwartym",
          "Umocnienie wiary",
          "Dostrajanie się do swoich instynktów",
          "Bycie chętnym lub ciekawym",
          "Odkrywanie swojego potencjału",
          "Innowacje i zmiany",
        ],
        shadow: [
          "Bycie łatwowiernym i naiwnym",
          "Podejmowanie niepotrzebnego ryzyka",
          "Nie być poważnym, gdy jest to wymagane",
          "Bycie głupim lub rozproszonym",
          "Brak doświadczenia",
          "Nie przestrzeganie ugruntowanych tradycji i ograniczeń",
          "Zachowywanie się niewłaściwie",
        ],
      },
      Archetype: "Boski szaleniec",
      Numerology: "0 (poza skalą; czysty potencjał)",
      Elemental: "Powietrze",
      Mistycyzm:
        "Adam przed upadkiem. Chrystus jako wędrowny święty szaleniec. Bóstwo owinięte ludzkim ciałem. Duch Święty.",
      "Questions to ask": [
        "Co bym zrobił, gdybym czuł się całkowicie wolny, by zrobić krok?",
        "Jak jestem chętny do bycia wrażliwym i otwartym?",
        "Jak doświadczenia z przeszłości mogą pomóc w tej nowej sytuacji?",
      ],
    },
    {
      name: "Magik",
      number: "1",
      omen: "dobry",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "m01.jpg",
      fortune_telling: [
        "Potężny człowiek może odegrać rolę w twoim życiu",
        "Twoja obecna sytuacja jest elementem znacznie większego planu",
      ],
      keywords: ["zdolność", "wzmocnienie", "działalność"],
      meanings: {
        light: [
          "Podjęcie odpowiednich działań",
          "Otrzymywanie wskazówek od siły wyższej",
          "Stawanie się kanałem woli Bożej",
          "Wyrażanie męskiej energii w odpowiedni sposób",
          "Bycie sobą w każdym calu",
        ],
        shadow: [
          "Napompowanie własnego ego",
          "Nadużywanie talentów",
          "Manipulowanie lub oszukiwanie innych",
          "Być zbyt agresywnym",
          "Wykorzystywanie tanich iluzji do olśnienia innych",
          "Odmowa inwestowania czasu i wysiłku potrzebnego do opanowania swojego rzemiosła",
          "Chodzenie na skróty",
        ],
      },
      Archetype: "Ego / Jaźń",
      Numerology: "1 (pochodzenie, jedność, nasiona)",
      Elemental: "Słońce/Merkury",
      Mistycyzm:
        "Thoth, egipski bóg mądrości, znany Grekom jako Hermes, a Rzymianom jako Merkury. Chrystus czyniący cuda. Brahma, Stwórca.",
      "Questions to ask": [
        "Do czego mam uprawnienia ?",
        "Jak moje umiejętności mogą wejść w grę?",
        "W jakim stopniu wykorzystuję swoje talenty?",
      ],
    },
    {
      name: "Wysoka Kapłanka",
      number: "2",
      omen: "dobry",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "m02.jpg",
      fortune_telling: [
        "Pojawienie się tajemniczej kobiety",
        "Ujawnienie sekretu sexualnego",
        "Ktoś wie więcej, niż chce ujawnić",
      ],
      keywords: ["intuicja", "odbicie", "czystość", "inicjacja"],
      meanings: {
        light: [
          "Wsłuchanie się w swoje uczucia i intuicje",
          "Odkrywanie duchowości niekonwencjonalnej",
          "Dochowanie tajemnic",
          "Być otwartym",
          "Refleksja zamiast działania",
          "Obserwowanie innych",
          "Zachowanie czystości",
        ],
        shadow: [
          "Być zdystansowanym",
          "Obsesja na punkcie tajemnic i spisków",
          "Odrzucanie przewodnictwa ducha lub intuicji",
          "Ujawnianie wszystkiego",
          "Ignorowanie przeczuć",
          "Odmowa zaangażowania się, nawet jeśli jest to najlepsza opcja",
        ],
      },
      Archetype: "Dziewica / Dziewica",
      Numerology: "2 (podział, debata, dwoistość)",
      Elemental: "Księżyc",
      Mistycyzm:
        "Kobiecy aspekt boskości, wyjątkowość wyrażana przez dziewictwo, jak w przypadku Maryi Panny lub Izydy.",
      "Questions to ask": [
        "Co może zrobić buntownik przeciwko tradycji ?",
        "Czego się nie mówi ani nie ujawnia?",
        "Co można osiągnąć dzięki obserwacji i refleksji?",
      ],
    },
    {
      name: "Cesarzowa",
      number: "3",
      omen: "dobry",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "m03.jpg",
      fortune_telling: [
        "W Twoim otoczeniu pojawi się ciąża",
        "Nadchodzi okazja do zaangażowania się w relację z wyjątkową seksualnością",
        "Strzeż się tendencji do uzależnień",
      ],
      keywords: ["płodność", "wydajność", "dojrzałość", "pielęgnacja"],
      meanings: {
        light: [
          "Pilęgnowanie siebie i innych",
          "Czczenie swojego ciała",
          "Rodzenie (dosłownie lub w przenośni) dzieci",
          "Rozkoszowanie się luksusem",
          "Matkowanie otaczającym Cię osóbom w pozytywny sposób",
          "Cieszenie się swoją seksualnością",
          "Załatwianie spraw",
        ],
        shadow: [
          "Przesada",
          "Być chciwym",
          "Duszenie kogoś nadmierną uwagą",
          "Wyniszczanie innych  przez bycie nadopiekuńczym",
          "Obsesja na punkcie produktywności",
        ],
      },
      Archetype: "Matka",
      Numerology: "3 (wyrażenie sieibe, produktywność, wynik)",
      Elemental: "Wenus",
      Mistycyzm:
        "Gaja, Matka Ziemia, Isztar, Demeter – dojrzała , reprodukcyjna boskość żeńska w każdej postaci. Także Afrodyta i Turan ",
      "Questions to ask": [
        "Co zrobiłaby zatroskana i zdolna matka ?",
        "Co mogę zrobić, aby podkreślić rozwój?",
        "Jak mogę celebrować własną zmysłowość i seksualność?",
      ],
    },
    {
      name: "Cesarz",
      number: "4",
      omen: "zły",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "m04.jpg",
      fortune_telling: [
        "Pojawienie się ojca",
        "Nowy pracodawca lub autorytet da Ci wytyczne",
        "Spodziewaj się poprawiania przez innych w najbliższej przyszłości",
      ],
      keywords: ["autorytet", "regulowanie", "kierunek", "Struktura"],
      meanings: {
        light: [
          "Bycie władczym",
          "Definiowanie granic",
          "Kierowanie pracą",
          "Przekazywanie jasnych wytycznych",
          "Kontrolowanie siebie i innych",
          "Temperowanie agresywnej męskości mądrością i doświadczeniem",
        ],
        shadow: [
          "Mikrozarządzanie",
          "Miażdżenie kreatywności innych swoim szorstkim podejściem",
          "Uporczywe dążenie do pójścia własną drogą",
          "Dyktatorski sposób myślenia",
          "Używanie siły, aby osiągnąć swoje cele i utrzymać porządek",
        ],
      },
      Archetype: "Ojciec",
      Numerology: "4 (stabilność, równość, wytrwałość)",
      Elemental: "Mars/Baran",
      Mistycyzm:
        "Bogowie rodzaju męskiego, w tym Bóg hebrajski, Bóg chrześcijański, Allah i Zeus. Patriarchowie (Abraham) i prawodawcy (Mojżesz). Wisznu, Zachowawca.",
      "Questions to ask": [
        "W jaki sposób kwestia kontroli lub regulacji wpływa na tę sytuację?",
        "Co zrobiłby współczujący, ale surowy ojciec ?",
        "Co wymaga większej kontroli?",
      ],
    },
    {
      name: "Hierofant",
      number: "5",
      omen: "zły",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "m05.jpg",
      fortune_telling: [
        "Spodziewaj się, że zostaniesz przyłapany na występku i odpowiednio ukarany",
        "Módl się o przebaczenie i wyznajcie winy",
        "W twoim życiu pojawi się bardziej doświadczony mężczyzna, przywódca duchowy lub ojciec",
      ],
      keywords: ["przewodnictwo", "wiedza", "objawienie", "wiara"],
      meanings: {
        light: [
          "Nauczanie lub prowadzenie innych",
          "Poszukiwanie prawdy",
          "Proszenie o przewodnictwo siły wyższej",
          "Uznanie mądrość i doświadczenie innych",
          "Zaangażowanie w serdeczne rytuały",
          "Zgłaszanie się na ochotnika",
        ],
        shadow: [
          "Wykorzystywanie doświadczenia jako sposobu manipulowania lub wprowadzania w błąd innych",
          "Być dogmatycznym",
          "Faworyzowanie tradycji ponad to, co jest celowe lub konieczne",
          "Przechodzenie przez niepotrzebne rytuały",
          "Ukryta mądrość",
        ],
      },
      Archetype: "Strażnik / Kościół / Wiara",
      Numerology: "5 (niestabilność, opór, konfrontacja, ewolucja)",
      Elemental: "Byk/Ziemia",
      Mistycyzm:
        "Chrystus, apostoł Piotr, Budda, Mahomet. Papieże, kapłani i orędownicy wszystkich wyznań i tradycji",
      "Questions to ask": [
        "Jaką rolę może odgrywać tradycja lub religia w tej sytuacji?",
        "Kto jest autorem zasad? Kto je egzekwuje? Dlaczego?",
        "Jak doświadczony przewodnik może wpłynąć na tę sytuację?",
      ],
    },
    {
      name: "Kochankowie",
      number: "6",
      omen: "dobry",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "m06.jpg",
      fortune_telling: [
        "Rozkwitnie nowy związek miłosny lub zawodowy",
        "Pojawią się okazję do intensywnych przeżyć seksualnych",
        "Nieoczekiwany przyjaciel stanie się kochankiem",
      ],
      keywords: ["miłość", "pasja", "jedność", "wybór"],
      meanings: {
        light: [
          "Bycie zakochanym",
          "Okazywanie swojej miłości innym",
          "Wyrażanie namiętności lub romantycznych uczuć",
          "Dopasowywanie się do grup lub podobnie myślących ludzi",
          "Łączenie ludzi",
          "Podejmowanie świadomych decyzji",
        ],
        shadow: [
          "Wyniszczająca pasja",
          "Dopuszczenie niezdrowego pragnienia miłości do motywowania destrukcyjnych zachowań",
          "Rozbijanie jedności innych",
          "Działanie przeciwko tym, którym na Tobie zależy",
          "Błędne decyzje",
        ],
      },
      Archetype: "Kochanek / przebudzenie seksualne",
      Numerology: "6 (współpraca, współpraca, interakcja)",
      Elemental: "Bliźnięta",
      Mistycyzm:
        "Oczywiście Adam i Ewa, którzy są przedstawieni w taliach inspirowanych RWS. Również Wenus i Kupidyn, Afrodyta i Eros.",
      "Questions to ask": [
        "Co kieruje moimi wyborami?",
        "Do czego prowadzi mnie serce ?",
        "Jak ta decyzja może zmienić mnie jako osobę?",
      ],
    },
    {
      name: "Rydwan",
      number: "7",
      omen: "dobry",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "m07.jpg",
      fortune_telling: [
        "Zwycięstwo jest pewne",
        "Idź naprzód ze wszystkimi planami",
        "Strzeż się zazdrości innych",
      ],
      keywords: ["postęp", "zwycięstwo", "triumf", "powodzenie"],
      meanings: {
        light: [
          "Przełamywanie barier",
          "Dążenie do przodu z ufnością i autorytetem",
          "Sięganie po sukces",
          "Wkładanie wysiłku dla całkowitego zwycięstwa",
          "Ustanowienie siebie liderem",
        ],
        shadow: [
          "Nie branie pod uwagę oczekiwań innych",
          "Koncentrowanie się bardziej na przeszłych sukcesach niż na przyszłych możliwościach",
          "Impulsywne zachowanie",
        ],
      },
      Archetype: "Zwycięski bohater",
      Numerology: "7 (wyobraźnia, praca wewnętrzna, psychologia)",
      Elemental: "Rak",
      Mistycyzm:
        "Odyseusz. Jazon. Poszukiwanie Świętego Graala. Triumfalny wjazd Chrystusa do Jerozolimy.",
      "Questions to ask": [
        "W jakim stopniu doszedłem? Jakie będzie moje następne wyzwanie ?",
        "Jak mogę najlepiej wykorzystać dotychczasowe osiągnięcia ?",
        "Jakie byłyby kryteria prawdziwego i znaczącego sukcesu? ",
      ],
    },
    {
      name: "Siła",
      number: "8",
      omen: "zły",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "m08.jpg",
      fortune_telling: [
        "Twoja samokontrola zostanie wystawiona na próbę",
        "Kobieta będzie dążyła do zmiany partnera lub kochanka",
        "Jesteś silną osobą",
      ],
      keywords: ["dyscyplina", "śmiałość", "moc", "witalność"],
      meanings: {
        light: [
          "Nakładanie na siebie ograniczeń dla własnej korzyści",
          "Opanowanie swoich namiętności pod kontrolą rozsądku",
          "Opieranie się impulsom, które działają wbrew twoim najlepszym interesom",
          "Odważne działanie",
        ],
        shadow: [
          "Pobłażanie słabości, nawet jeśli wiesz, że zaszkodzi to Twojemu zdrowiu i szczęściu",
          "Trwanie w uzależnieniu",
          "Pozwalanie, by twoje instynkty cię oswoiły i podbiły",
          "Niezajmowanie stanowiska, gdy jest to konieczne",
        ],
      },
      Archetype: "Prawo",
      Numerology: "8 (ruch, praca) lub 11 = 1 + 1 = 2 (debata, dwoistość)",
      Żywiołaki: "Waga lub Lew",
      Mistycyzm:
        "Temida lub Justitia . Ma'at . Salomon dzielący dziecko. Miecz Damoklesa. Nadanie dziesięciu przykazań.",
      "Pytania, które warto zadać": [
        "W jakim stopniu Twoje życie (lub praca) jest zrównoważone?",
        "Jak osiągnąć większy obiektywizm?",
        "Jakie postępowanie byłoby sprawiedliwe dla wszystkich zainteresowanych?",
      ],
    },
    {
      name: "Pustelnik",
      number: "9",
      omen: "zły",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "m09.jpg",
      fortune_telling: [
        "Rozpoczęcie okresu samotności",
        "Odejście partnera",
        "Poszukiwanie miłości lub pieniędzy będzie się bezowocne",
      ],
      keywords: ["samotność", "doświadczenie", "bezruch", "wycofanie"],
      meanings: {
        light: [
          "Zostawanie lub poszukiwanie guru",
          "Ładowanie baterii duchowych lub twórczych",
          "Oświetlanie drogi tym z mniejszym doświadczeniem",
          "Cofanie się, aby zyskać lepszą perspektywę",
        ],
        shadow: [
          "Bycie samotnikiem",
          "Obawianie się kontaktu z innymi",
          "Stanie się wszechwiedzącym",
          "Ukrywanie swoich umiejętności i talentów ze strachu przed bezwartościowością",
        ],
      },
      Archetype: "Święty człowiek",
      Numerology: "9 (pełnia, gotowość, dojrzałość)",
      Elemental: "Panna",
      Mistycyzm:
        "Chrystus pościł przez 40 dni na pustyni. Chronos , bóg czasu. Ojciec Czas. Hermes.",
      "Questions to ask": [
        "Co by się stało, gdybym po prostu wycofał się i nie podjął żadnych działań?",
        "Jak mogę spojrzeć na sytuację z perspektywy?",
        "Kto przeszedł tę ścieżkę przede mną? Jak mogę pozyskać jego lub jej pomoc?",
      ],
    },
    {
      name: "Koło fortuny",
      number: "9",
      omen: "dobry",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "m10.jpg",
      fortune_telling: [
        "Niektóre wydarzenia są w rękach nieba",
        "Przeżyjesz coś co wydarzyło się już wcześniej",
        "Czeka Cię zmiana",
      ],
      keywords: ["szczęście", "losowość", "cykle", "karma", "los", "rewolucja"],
      meanings: {
        light: [
          "Pozwolenie na rozwój wydarzeń",
          "Dostrzeganie większego sensu w codziennych wydarzeniach",
          "Ufanie swojemu szczęściu",
          "Wypatrywanie cykli",
        ],
        shadow: [
          "Utrata pieniędzy w grach hazardowych",
          "Brak działania w celu urzeczywistnienia planu",
          "Przyjmowanie fatalistycznego podejścia do życia",
          "Walka z naturalnym biegiem wydarzeń",
        ],
      },
      Archetype: "Losy / Przeznaczenie",
      Numerology:
        "10 (ostateczność, zakończenie) i 10 = 1 + 0 = 1 (ziarno, szansa)",
      Elemental: "Jowisz",
      Mistycyzm:
        "Bóg w maszynie. Deus ex Machina . Clotho , Lachesis i Atropos . Fortuna.",
      "Questions to ask": [
        "Jak to wyzwanie pasuje do szerszego schematu?",
        "Jaką rolę odgrywa szczęście w moich okolicznościach?",
        "Co mogę kontrolować? Skąd mam wiedzieć, kiedy zrzec się kontroli?",
      ],
    },
  ],
};
