export default {
  description: "Karty tarota z podstawowymi informacjami",
  cards: [
    {
      name: "Głupiec",
      number: "0",
      omen: "zły",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/glupiec-1.jpg",
      fortune_telling: [
        "Wypatruj nowych projektów i nowych początków",
        "Przygotuj się na test Twojej wiary",
        "Coś nowego pojawi się na twojej drodze, bądź gotowy",
      ],
      keywords: ["wolność", "wiara", "brak doświadczenia", "niewinność"],
      meanings: {
        light: [
          "Uwolnienie się od ograniczeń",
          "Wyrażanie radośćci i młodzieńczy wigor",
          "Bycie otwartym",
          "Umocnienie wiary",
          "Dostrajanie się do swoich instynktów",
          "Bycie chętnym lub ciekawym",
          "Odkrywanie swojego potencjału",
          "Innowacje i zmiany",
        ],
        shadow: [
          "Bycie łatwowiernym i naiwnym",
          "Podejmowanie niepotrzebnego ryzyka",
          "Nie być poważnym, gdy jest to wymagane",
          "Bycie głupim lub rozproszonym",
          "Brak doświadczenia",
          "Nie przestrzeganie ugruntowanych tradycji i ograniczeń",
          "Zachowywanie się niewłaściwie",
        ],
      },
      Archetype: "Boski szaleniec",
      Numerology: "0 (poza skalą; czysty potencjał)",
      Elemental: "Powietrze",
      love: "W kontekście uczuć i miłości, Głupiec może oznaczać podejmowanie ryzyka w imię miłości i szukanie przygód z ukochanym. Może to być również sygnał, że trzeba otworzyć się na nowe możliwości i doświadczenia w związku. Jeśli chodzi o nasze uczucia do drugiej osoby, Głupiec może oznaczać, że jesteśmy gotowi podejmować ryzyko i poświęcić się dla naszej miłości. Może to także sygnalizować, że jesteśmy bardzo zakochani i gotowi na wszystko dla drugiej połówki.",
      love_reverse:
        "Karta tarota Głupiec, może sugerować brak stabilności i poważnego podejścia do związku jeżeli jest w pozycji odwróconej, co może prowadzić do problemów i niestabilności w miłości. W takim przypadku, może to być sygnał, że należy uważać i dokładnie przemyśleć nasze działania w związku.",
      Mistics:
        "Adam przed upadkiem. Chrystus jako wędrowny święty szaleniec. Bóstwo owinięte ludzkim ciałem. Duch Święty.",
      Questions_to_ask: [
        "Co bym zrobił, gdybym czuł się całkowicie wolny, by zrobić krok?",
        "Jak jestem chętny do bycia wrażliwym i otwartym?",
        "Jak doświadczenia z przeszłości mogą pomóc w tej nowej sytuacji?",
      ],
    },
    {
      name: "Mag",
      number: "1",
      omen: "dobry",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/mag.jpg",
      fortune_telling: [
        "Potężny człowiek może odegrać rolę w twoim życiu",
        "Twoja obecna sytuacja jest elementem znacznie większego planu",
      ],
      keywords: ["zdolność", "wzmocnienie", "działalność"],
      meanings: {
        light: [
          "Podjęcie odpowiednich działań",
          "Otrzymywanie wskazówek od siły wyższej",
          "Stawanie się kanałem woli Bożej",
          "Wyrażanie męskiej energii w odpowiedni sposób",
          "Bycie sobą w każdym calu",
        ],
        shadow: [
          "Napompowanie własnego ego",
          "Nadużywanie talentów",
          "Manipulowanie lub oszukiwanie innych",
          "Być zbyt agresywnym",
          "Wykorzystywanie tanich iluzji do olśnienia innych",
          "Odmowa inwestowania czasu i wysiłku potrzebnego do opanowania swojego rzemiosła",
          "Chodzenie na skróty",
        ],
      },
      Archetype: "Ego / Jaźń",
      Numerology: "1 (pochodzenie, jedność, nasiona)",
      Elemental: "Słońce/Merkury",
      love: "Mag może być postrzegany jako karta pomyślności w miłości, wskazując na silne uczucia i dobre relacje między partnerami. Może również sugerować, że osoba, która otrzymała tę kartę, jest silna i zdeterminowana w swoich uczuciach, co pozwala jej na lepsze radzenie sobie z trudnościami w miłości.",
      love_reverse:
        "W pozycji odwróconej Mag może być zwiastunem problemów w życiu miłosnym. Może sugerować, że osoba, która otrzymała tę kartę, jest zbyt zdominowana przez swoje uczucia i potrzeby, co może prowadzić do konfliktów w związku. Mogą również pojawić się problemy związane z komunikacją i niezrozumieniem między partnerami.",
      Mistics:
        "Thoth, egipski bóg mądrości, znany Grekom jako Hermes, a Rzymianom jako Merkury. Chrystus czyniący cuda. Brahma, Stwórca.",
      Questions_to_ask: [
        "Do czego mam uprawnienia ?",
        "Jak moje umiejętności mogą wejść w grę?",
        "W jakim stopniu wykorzystuję swoje talenty?",
      ],
    },
    {
      name: "Kapłanka",
      number: "2",
      omen: "dobry",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/kaplanka.jpg",
      fortune_telling: [
        "Pojawienie się tajemniczej kobiety",
        "Ujawnienie sekretu sexualnego",
        "Ktoś wie więcej, niż chce ujawnić",
      ],
      keywords: ["intuicja", "odbicie", "czystość", "inicjacja"],
      meanings: {
        light: [
          "Wsłuchanie się w swoje uczucia i intuicje",
          "Odkrywanie duchowości niekonwencjonalnej",
          "Dochowanie tajemnic",
          "Być otwartym",
          "Refleksja zamiast działania",
          "Obserwowanie innych",
          "Zachowanie czystości",
        ],
        shadow: [
          "Być zdystansowanym",
          "Obsesja na punkcie tajemnic i spisków",
          "Odrzucanie przewodnictwa ducha lub intuicji",
          "Ujawnianie wszystkiego",
          "Ignorowanie przeczuć",
          "Odmowa zaangażowania się, nawet jeśli jest to najlepsza opcja",
        ],
      },
      Archetype: "Dziewica / Dziewica",
      Numerology: "2 (podział, debata, dwoistość)",
      Elemental: "Księżyc",
      love: "Jeśli jesteś singlem, karta ta może oznaczać, że jesteś gotów na nowe miłosne doświadczenia i że twoja intuicja ci pomoże w znalezieniu odpowiedniej osoby. Jeśli jesteś w związku, karta ta może oznaczać, że powinieneś skupić się na swoich uczuciach i potrzebach oraz być bardziej uważnym na potrzeby drugiej osoby. Może również oznaczać, że druga osoba czuje się bezpiecznie i potrafi nam zaufać w relacji. Jest to pozytywny znak, który sugeruje, że jesteśmy w stanie budować silny i trwały związek.",
      love_reverse:
        "Jeśli karta pojawia się w pozycji negatywnej, może oznaczać, że jesteśmy zbyt skupieni na sobie i swoich potrzebach i nie jesteśmy w stanie dostrzec potrzeb drugiej osoby. Być może brakuje nam odpowiedniej komunikacji i słuchania drugiej osoby.",
      Mistics:
        "Kobiecy aspekt boskości, wyjątkowość wyrażana przez dziewictwo, jak w przypadku Maryi Panny lub Izydy.",
      Questions_to_ask: [
        "Co może zrobić buntownik przeciwko tradycji ?",
        "Czego się nie mówi ani nie ujawnia?",
        "Co można osiągnąć dzięki obserwacji i refleksji?",
      ],
    },
    {
      name: "Cesarzowa",
      number: "3",
      omen: "dobry",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/cesarzowa.jpg",
      fortune_telling: [
        "W Twoim otoczeniu pojawi się ciąża",
        "Nadchodzi okazja do zaangażowania się w relację z wyjątkową seksualnością",
        "Strzeż się tendencji do uzależnień",
      ],
      keywords: ["płodność", "wydajność", "dojrzałość", "pielęgnacja"],
      meanings: {
        light: [
          "Pilęgnowanie siebie i innych",
          "Czczenie swojego ciała",
          "Rodzenie (dosłownie lub w przenośni) dzieci",
          "Rozkoszowanie się luksusem",
          "Matkowanie otaczającym Cię osóbom w pozytywny sposób",
          "Cieszenie się swoją seksualnością",
          "Załatwianie spraw",
        ],
        shadow: [
          "Przesada",
          "Być chciwym",
          "Duszenie kogoś nadmierną uwagą",
          "Wyniszczanie innych  przez bycie nadopiekuńczym",
          "Obsesja na punkcie produktywności",
        ],
      },
      Archetype: "Matka",
      Numerology: "3 (wyrażenie sieibe, produktywność, wynik)",
      Elemental: "Wenus",
      love: "Jeśli jesteś singlem i w swoim rozkładzie tarota uzyskałeś Cesarzową, to jest to dobry znak, że w twoim życiu miłosnym pojawi się osoba, która będzie mocna, niezależna i zdecydowana. Jeśli jesteś już w związku, Cesarzowa oznacza, że twoje uczucie jest silne i trwałe, a Ty i Twój partner jesteście w stanie utrzymać swoje relacje w stabilnej równowadze.",
      love_reverse:
        "Cesarzowa także może wskazywać na trudności w twoim życiu miłosnym, jeśli jest połączona z kartami, które oznaczają konflikty lub trudności lun jest w pozycji odwróconej. W takim przypadku, Cesarzowa może sugerować, że w twoim związku trzeba będzie walczyć o swoje uczucia, aby utrzymać je silne i trwałe.",
      Mistics:
        "Gaja, Matka Ziemia, Isztar, Demeter – dojrzała , reprodukcyjna boskość żeńska w każdej postaci. Także Afrodyta i Turan ",
      Questions_to_ask: [
        "Co zrobiłaby zatroskana i zdolna matka ?",
        "Co mogę zrobić, aby podkreślić rozwój?",
        "Jak mogę celebrować własną zmysłowość i seksualność?",
      ],
    },
    {
      name: "Cesarz",
      number: "4",
      omen: "zły",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/cesarz.jpg",
      fortune_telling: [
        "Pojawienie się ojca",
        "Nowy pracodawca lub autorytet da Ci wytyczne",
        "Spodziewaj się poprawiania przez innych w najbliższej przyszłości",
      ],
      keywords: ["autorytet", "regulowanie", "kierunek", "Struktura"],
      meanings: {
        light: [
          "Bycie władczym",
          "Definiowanie granic",
          "Kierowanie pracą",
          "Przekazywanie jasnych wytycznych",
          "Kontrolowanie siebie i innych",
          "Temperowanie agresywnej męskości mądrością i doświadczeniem",
        ],
        shadow: [
          "Mikrozarządzanie",
          "Miażdżenie kreatywności innych swoim szorstkim podejściem",
          "Uporczywe dążenie do pójścia własną drogą",
          "Dyktatorski sposób myślenia",
          "Używanie siły, aby osiągnąć swoje cele i utrzymać porządek",
        ],
      },
      Archetype: "Ojciec",
      Numerology: "4 (stabilność, równość, wytrwałość)",
      Elemental: "Mars/Baran",
      love: "Jeśli otrzymasz tę kartę przy rozkładaniu tarota na temat swojego życia miłosnego, może to oznaczać, że masz silne i trwałe uczucie do swojego partnera, a twój związek jest oparty na wzajemnym zaufaniu i zrozumieniu. Może to także wskazywać, że jesteś w stanie kontrolować sytuację w swoim związku i że twoja relacja jest mocna i stabilna.",
      love_reverse:
        " Jeśli karta pojawia się w pozycji odwróconej lub inne karty nakreślają negatywny kontekst, Cesarz może wtedy oznaczać brak emocjonalnej stabilności lub niepewność w związku. W takim przypadku, karta może również sugerować, że twój partner jest zdominowany i kontrolowany przez swoje emocje, co może prowadzić do problemów w waszej relacji.",
      Mistics:
        "Bogowie rodzaju męskiego, w tym Bóg hebrajski, Bóg chrześcijański, Allah i Zeus. Patriarchowie (Abraham) i prawodawcy (Mojżesz). Wisznu, Zachowawca.",
      Questions_to_ask: [
        "W jaki sposób kwestia kontroli lub regulacji wpływa na tę sytuację?",
        "Co zrobiłby współczujący, ale surowy ojciec ?",
        "Co wymaga większej kontroli?",
      ],
    },
    {
      name: "Kapłan",
      number: "5",
      omen: "zły",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/kaplan.jpg",
      fortune_telling: [
        "Spodziewaj się, że zostaniesz przyłapany na występku i odpowiednio ukarany",
        "Módl się o przebaczenie i wyznajcie winy",
        "W twoim życiu pojawi się bardziej doświadczony mężczyzna, przywódca duchowy lub ojciec",
      ],
      keywords: ["przewodnictwo", "wiedza", "objawienie", "wiara"],
      meanings: {
        light: [
          "Nauczanie lub prowadzenie innych",
          "Poszukiwanie prawdy",
          "Proszenie o przewodnictwo siły wyższej",
          "Uznanie mądrość i doświadczenie innych",
          "Zaangażowanie w serdeczne rytuały",
          "Zgłaszanie się na ochotnika",
        ],
        shadow: [
          "Wykorzystywanie doświadczenia jako sposobu manipulowania lub wprowadzania w błąd innych",
          "Być dogmatycznym",
          "Faworyzowanie tradycji ponad to, co jest celowe lub konieczne",
          "Przechodzenie przez niepotrzebne rytuały",
          "Ukryta mądrość",
        ],
      },
      Archetype: "Strażnik / Kościół / Wiara",
      Numerology: "5 (niestabilność, opór, konfrontacja, ewolucja)",
      Elemental: "Byk/Ziemia",
      love: "Jeśli jesteś samotną osobą i zastanawiasz się, jak Arcykapłan w tarocie wpłynie na twoje życie uczuciowe, to istnieje kilka wskazówek, na które powinieneś zwrócić uwagę. Przede wszystkim, karta sugeruje, że ​​musisz być otwarty na nowe idee, myśli i doświadczenia, aby znaleźć swoją prawdziwą miłość. Musisz szukać duchowego partnera, z kim zbudujesz silny związek oparty na duchowej zgodzie i zrozumieniu. Jeśli z kolei karta papieża pojawia się w kontekście twojego obecnego związku, to może sugerować, że ​​jest to związek oparty na duchowej i intelektualnej więzi. Może to być znak, że twoje uczucia względem swojego partnera są głębokie i silne, ale jednocześnie istnieje potrzeba pracy nad rozwijaniem związku, aby nie tylko pogłębiać wasze więzi emocjonalne, ale także te intelektualne i duchowe.",
      love_reverse:
        "Warto jednak pamiętać, że jak każda karta Tarota, również Kapłan ma swoje wady i pułapki. Jedną z największych wad, jaką reprezentuje, jest nadmierna ostrożność i skłonność do nadmiernego zastanawiania się nad każdą decyzją. To może prowadzić do stagnacji, co w kontekście miłości i związków oznacza brak postępu i zmian, a w konsekwencji może być szkodliwe dla związku.",
      Mistics:
        "Chrystus, apostoł Piotr, Budda, Mahomet. Papieże, kapłani i orędownicy wszystkich wyznań i tradycji",
      Questions_to_ask: [
        "Jaką rolę może odgrywać tradycja lub religia w tej sytuacji?",
        "Kto jest autorem zasad? Kto je egzekwuje? Dlaczego?",
        "Jak doświadczony przewodnik może wpłynąć na tę sytuację?",
      ],
    },
    {
      name: "Kochankowie",
      number: "6",
      omen: "dobry",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/kochankowie.jpg",
      fortune_telling: [
        "Rozkwitnie nowy związek miłosny lub zawodowy",
        "Pojawią się okazję do intensywnych przeżyć seksualnych",
        "Nieoczekiwany przyjaciel stanie się kochankiem",
      ],
      keywords: ["miłość", "pasja", "jedność", "wybór"],
      meanings: {
        light: [
          "Bycie zakochanym",
          "Okazywanie swojej miłości innym",
          "Wyrażanie namiętności lub romantycznych uczuć",
          "Dopasowywanie się do grup lub podobnie myślących ludzi",
          "Łączenie ludzi",
          "Podejmowanie świadomych decyzji",
        ],
        shadow: [
          "Wyniszczająca pasja",
          "Dopuszczenie niezdrowego pragnienia miłości do motywowania destrukcyjnych zachowań",
          "Rozbijanie jedności innych",
          "Działanie przeciwko tym, którym na Tobie zależy",
          "Błędne decyzje",
        ],
      },
      Archetype: "Kochanek / przebudzenie seksualne",
      Numerology: "6 (współpraca, współpraca, interakcja)",
      Elemental: "Bliźnięta",
      love: "W temacie uczuć i miłości, karta Kochankowie może wskazywać na pojawienie się nowych, intensywnych uczuć lub związków. Karta ta może być też interpretowana jako znak, że miłość i namiętność wkrótce pojawią się w życiu danej osoby.",
      love_reverse:
        "Kochankowie nie zawsze oznaczają pomyślność, ponieważ w tej pozycji karta ta może też symbolizować trudne wybory i decyzje związane z uczuciami. Może to sugerować, że osoba będzie musiała wybrać między dwoma potencjalnymi partnerami lub wybrać, czy chce poświęcić swoją karierę dla miłości.",
      Mistics:
        "Oczywiście Adam i Ewa, którzy są przedstawieni w taliach inspirowanych RWS. Również Wenus i Kupidyn, Afrodyta i Eros.",
      Questions_to_ask: [
        "Co kieruje moimi wyborami?",
        "Do czego prowadzi mnie serce ?",
        "Jak ta decyzja może zmienić mnie jako osobę?",
      ],
    },
    {
      name: "Rydwan",
      number: "7",
      omen: "dobry",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/rydwan.jpg",
      fortune_telling: [
        "Zwycięstwo jest pewne",
        "Idź naprzód ze wszystkimi planami",
        "Strzeż się zazdrości innych",
      ],
      keywords: ["postęp", "zwycięstwo", "triumf", "powodzenie"],
      meanings: {
        light: [
          "Przełamywanie barier",
          "Dążenie do przodu z ufnością i autorytetem",
          "Sięganie po sukces",
          "Wkładanie wysiłku dla całkowitego zwycięstwa",
          "Ustanowienie siebie liderem",
        ],
        shadow: [
          "Nie branie pod uwagę oczekiwań innych",
          "Koncentrowanie się bardziej na przeszłych sukcesach niż na przyszłych możliwościach",
          "Impulsywne zachowanie",
        ],
      },
      Archetype: "Zwycięski bohater",
      Numerology: "7 (wyobraźnia, praca wewnętrzna, psychologia)",
      Elemental: "Rak",
      love: "W odniesieniu do miłości i uczuć, karta Rydwan może wskazywać na silne emocje i pożądanie. Wskazuje na dynamiczny, ekscytujący i zdecydowany charakter, który z pewnością przyciągnie uwagę partnera. Jeśli jesteś w związku i pytasz o swoje uczucia, ta karta sugeruje, że twoje relacje są pełne energii i ruchu. Wskazuje również na fakt, że jesteś gotów na zmiany w swoim życiu miłosnym i podejmujesz działania, aby osiągnąć to, czego pragniesz.",
      love_reverse:
        "Karta Rydwan w pozycji odwróconej może wskazywać na niezdecydowanie i brak kontroli nad sytuacją. Może wskazywać na potrzebę zwolnienia tempa i zastanowienia się nad swoimi wyborami. Może także wskazywać na konflikt lub brak porozumienia w związku.",
      Mistics:
        "Odyseusz. Jazon. Poszukiwanie Świętego Graala. Triumfalny wjazd Chrystusa do Jerozolimy.",
      Questions_to_ask: [
        "W jakim stopniu doszedłem? Jakie będzie moje następne wyzwanie ?",
        "Jak mogę najlepiej wykorzystać dotychczasowe osiągnięcia ?",
        "Jakie byłyby kryteria prawdziwego i znaczącego sukcesu? ",
      ],
    },
    {
      name: "Siła (Moc)",
      number: "8",
      omen: "zły",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/sila.jpg",
      fortune_telling: [
        "Twoja samokontrola zostanie wystawiona na próbę",
        "Kobieta będzie dążyła do zmiany partnera lub kochanka",
        "Jesteś silną osobą",
      ],
      keywords: ["dyscyplina", "śmiałość", "moc", "witalność"],
      meanings: {
        light: [
          "Nakładanie na siebie ograniczeń dla własnej korzyści",
          "Opanowanie swoich namiętności pod kontrolą rozsądku",
          "Opieranie się impulsom, które działają wbrew twoim najlepszym interesom",
          "Odważne działanie",
        ],
        shadow: [
          "Pobłażanie słabości, nawet jeśli wiesz, że zaszkodzi to Twojemu zdrowiu i szczęściu",
          "Trwanie w uzależnieniu",
          "Pozwalanie, by twoje instynkty cię oswoiły i podbiły",
          "Niezajmowanie stanowiska, gdy jest to konieczne",
        ],
      },
      Archetype: "Prawo",
      Numerology: "8 (ruch, praca) lub 11 = 1 + 1 = 2 (debata, dwoistość)",
      Elemental: "Waga lub Lew",
      love: "W kontekście miłości, karta Siła oznacza, że nasza miłość i uczucia są bardzo silne i zdolne przetrwać trudne chwile. Ta karta mówi o pozytywnych i silnych uczuciach, które przynoszą radość i spełnienie. Osoba, która otrzymuje tę kartę, może czuć się pewna swojego partnera i swojego związku. Oznacza to, że osoba ta jest gotowa do walki o swoją miłość i gotowa jest na trudne wyzwania, jakie mogą się pojawić na drodze do szczęśliwego związku. Może również oznaczać, że nasze uczucia są na tyle silne, że przyciągają do nas pozytywne energie i ludzi, którzy podzielają nasze wartości i cele życiowe.",
      love_reverse:
        "Karta Siła w pozycji odwróconej pokazuje, że musimy zmierzyć się z pewnymi wyzwaniami, które mogą wpłynąć na nasze relacje miłosne. Często oznacza to, że musimy być bardziej stanowczy i bardziej zdeterminowani, aby przetrwać trudne chwile. Karta ta mówi nam, że musimy być gotowi na działanie i zdecydowane kroki, aby utrzymać nasze uczucia i relacje w dobrym stanie.",
      Mistics:
        "Temida lub Justitia . Ma'at . Salomon dzielący dziecko. Miecz Damoklesa. Nadanie dziesięciu przykazań.",
      Questions_to_ask: [
        "W jakim stopniu Twoje życie (lub praca) jest zrównoważone?",
        "Jak osiągnąć większy obiektywizm?",
        "Jakie postępowanie byłoby sprawiedliwe dla wszystkich zainteresowanych?",
      ],
    },
    {
      name: "Pustelnik",
      number: "9",
      omen: "zły",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/pustenik.jpg",
      fortune_telling: [
        "Rozpoczęcie okresu samotności",
        "Odejście partnera",
        "Poszukiwanie miłości lub pieniędzy będzie się bezowocne",
      ],
      keywords: ["samotność", "doświadczenie", "bezruch", "wycofanie"],
      meanings: {
        light: [
          "Zostawanie lub poszukiwanie guru",
          "Ładowanie baterii duchowych lub twórczych",
          "Oświetlanie drogi tym z mniejszym doświadczeniem",
          "Cofanie się, aby zyskać lepszą perspektywę",
        ],
        shadow: [
          "Bycie samotnikiem",
          "Obawianie się kontaktu z innymi",
          "Stanie się wszechwiedzącym",
          "Ukrywanie swoich umiejętności i talentów ze strachu przed bezwartościowością",
        ],
      },
      Archetype: "Święty człowiek",
      Numerology: "9 (pełnia, gotowość, dojrzałość)",
      Elemental: "Panna",
      love: "Karta Pustelnik nie oznacza koniecznie negatywnych skutków dla uczuć i miłości. Może ona bowiem wskazywać na potrzebę czasu dla siebie i swoich rozmyślań, co w efekcie może prowadzić do większej samoakceptacji i gotowości do nawiązywania relacji z innymi ludźmi. Może także sugerować, że w życiu uczuciowym pojawi się ktoś, kto będzie dla nas ważny i będzie wpływał na nasze życie w pozytywny sposób. Jednakże, aby to się stało, musimy najpierw poradzić sobie z naszymi własnymi emocjami i zacząć działać w kierunku pozytywnych zmian.",
      love_reverse:
        "Jeśli karta pojawia się w pozycji odwróconej może sugerować, że jedna z osób w związku odczuwa potrzebę oddalenia się od partnera i skupienia się na swoich własnych sprawach. Może to wynikać z potrzeby rozwoju osobistego lub związane być z problemami emocjonalnymi. Jeśli natomiast karta ta pojawia się w kontekście poszukiwania miłości, może oznaczać konieczność samorefleksji i odkrywania swoich potrzeb i pragnień. Osoba, która odczuwa potrzebę samotności i izolacji, musi najpierw poradzić sobie z własnymi emocjami, zanim będzie mogła nawiązać prawdziwe i pełnowartościowe związki z innymi ludźmi",
      Mistics:
        "Chrystus pościł przez 40 dni na pustyni. Chronos , bóg czasu. Ojciec Czas. Hermes.",
      Questions_to_ask: [
        "Co by się stało, gdybym po prostu wycofał się i nie podjął żadnych działań?",
        "Jak mogę spojrzeć na sytuację z perspektywy?",
        "Kto przeszedł tę ścieżkę przede mną? Jak mogę pozyskać jego lub jej pomoc?",
      ],
    },
    {
      name: "Koło fortuny",
      number: "10",
      omen: "dobry",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/kolo-fortuny.jpg",
      fortune_telling: [
        "Niektóre wydarzenia są w rękach nieba",
        "Przeżyjesz coś co wydarzyło się już wcześniej",
        "Czeka Cię zmiana",
      ],
      keywords: ["szczęście", "losowość", "cykle", "karma", "los", "rewolucja"],
      meanings: {
        light: [
          "Pozwolenie na rozwój wydarzeń",
          "Dostrzeganie większego sensu w codziennych wydarzeniach",
          "Ufanie swojemu szczęściu",
          "Wypatrywanie cykli",
        ],
        shadow: [
          "Utrata pieniędzy w grach hazardowych",
          "Brak działania w celu urzeczywistnienia planu",
          "Przyjmowanie fatalistycznego podejścia do życia",
          "Walka z naturalnym biegiem wydarzeń",
        ],
      },
      Archetype: "Losy / Przeznaczenie",
      Numerology:
        "10 (ostateczność, zakończenie) i 10 = 1 + 0 = 1 (ziarno, szansa)",
      Elemental: "Jowisz",
      love: "W pozycji prostej, karta ta zazwyczaj oznacza zmiany, które niosą ze sobą pozytywne efekty. W kontekście miłości, karta ta może oznaczać, że wkrótce pojawi się nowa osoba w Twoim życiu lub istniejący związek przejdzie na nowy poziom. Ta karta sugeruje, że Twój los jest pozytywny i że będziesz w stanie wykorzystać swoje szczęście w miłości.",
      love_reverse:
        "Jednak w pozycji odwróconej, karta Koło fortuny może wskazywać na niepewność i niestabilność w związku lub w Twoim życiu uczuciowym. Oznacza to, że Twój los w miłości jest niepewny, a Twoje relacje mogą zmierzać w niewłaściwym kierunku. Może to oznaczać, że jesteś w stagnacji lub doświadczasz trudności w poruszaniu się naprzód w swoim życiu miłosnym.",
      Mistics:
        "Bóg w maszynie. Deus ex Machina . Clotho , Lachesis i Atropos . Fortuna.",
      Questions_to_ask: [
        "Jak to wyzwanie pasuje do szerszego schematu?",
        "Jaką rolę odgrywa szczęście w moich okolicznościach?",
        "Co mogę kontrolować? Skąd mam wiedzieć, kiedy zrzec się kontroli?",
      ],
    },
    {
      name: "Sprawiedliwość",
      number: "11",
      omen: "dobry",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/sprawiedliwosc.jpg",
      fortune_telling: [
        "Wkrótce zapadnie istotny wyrok prawny",
        "Ktoś podejmuje decyzję",
        "Pewne fakty wyjdą na jaw",
      ],
      keywords: ["saldo", "prawo", "uczciwość", "obiektywność"],
      meanings: {
        light: [
          "Podjęcie obiektywnej decyzji",
          "Dokładne rozważenie problemu przed podjęciem działań",
          "Odpowiednie skalowanie reakcji do sytuacji",
          "Zbieranie wszystkich faktów",
          "Rozpatrywanie dowodów",
          "Rozważanie",
        ],
        shadow: [
          "Dostarczanie ostrej krytyki",
          "Obsesja na punkcie zasad i przepisów",
          "Postępowanie zgodnie z instrukcją, nawet jeśli jest to destrukcyjne lub przynosi efekt przeciwny do zamierzonego",
          "Mylenie szybkich decyzji z podejmowanymi w odpowiednim czasie działaniami",
          "Odtwarzanie ulubionych",
        ],
      },
      Archetype: "Id",
      "Alfabet hebrajski": " Theth /Snake/9 lub Lamed/Rozpostarte ramiona/30",
      Numerology:
        "11 = 1 + 1 = 2 (debata, dwoistość) lub 8 (ruch, praca zewnętrzna)",
      Żywiołaki: "Lew lub Waga",
      love: "Kiedy ta karta pojawia się w kontekście miłości i uczuć, może to oznaczać, że nadszedł czas, aby zwrócić uwagę na równowagę w związku. Może to oznaczać, że musimy zadbać o to, aby relacja była oparta na uczciwości, lojalności i wzajemnym szacunku. Co do pytania o uczucia drugiej osoby do nas, może oznaczać, że nasz partner lub osoba, którą kochamy, jest uczciwa, lojalna i prawdomówna.",
      love_reverse:
        "Karta odwrócona może sygnalizować trudności w związku. Może to oznaczać, że relacja jest nierówna, a jedna strona traktuje drugą ze zbytnią surowością. Konieczne może być wprowadzenie bardziej równomiernych warunków w relacji, aby uniknąć bólu i konfliktów. Co do pytania o uczucia drugiej osoby do nas, może oznaczać, że ta osoba jest zbyt surowa lub bezwzględna w swoich postawach i podejściu do naszego związku",
      Mistics: "Samson. Herkules. Daniel w jaskini lwa. Bezgrzeszny Chrystus.",
      Questions_to_ask: [
        "Jak mogę zwiększyć swoją samodyscyplinę?",
        "Jakie zachowania mnie kuszą? Jak mogę się oprzeć?",
        "Z jakimi instynktami nadal walczę?",
      ],
    },
    {
      name: "Wisielec",
      number: "12",
      omen: "zły",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/wisielec.jpg",
      fortune_telling: [
        "Ujawniono zdrajcę",
        "Jeden z twoich przyjaciół działa przeciwko tobie",
        "Zmień swoje postępowanie lub ponieś konsekwencje",
      ],
      keywords: [
        "oświecenie",
        "poświęcenie",
        "perspektywiczny",
        "zawieszenie",
        "odwrócenia",
      ],
      meanings: {
        light: [
          "Dostrzeganie możliwości rozwoju w przykrych zdarzeniach",
          "Doświadczanie dramatycznej zmiany osobistej perspektywy",
          "Jak najlepiej wykorzystać nieprzewidzianą zmianę w swoim życiu lub pracy",
          "Zawieszenie niewiary",
          "Składanie ofiar",
        ],
        shadow: [
          "Być niewiernym wobec siebie i swoich wartości",
          "Odmowa poświęceń, gdy jest to właściwe",
          "Odmowa przystosowania się do nowych sytuacji",
          "Obwinianie innych",
          "Zarabianie kosztem innych",
        ],
      },
      Archetype: "Zdrajca",
      "Alfabet hebrajski": " Mem /woda/40",
      Numerology: "12 = 1 + 2 = 3 (wyrażenie, produktywność, wynik)",
      Elemental: "Woda",
      love: "W pozycji prostej, karta ta odnosi się do czasu oczekiwania na coś ważnego lub decyzji, której nie jesteśmy jeszcze w stanie podjąć. Może to oznaczać, że w kwestiach miłosnych znajdujemy się w punkcie zwrotnym i potrzebujemy czasu, aby zastanowić się nad tym, co chcemy zrobić dalej. Wisielec może symbolizować czas, który musimy poświęcić na samorozwój i pracę nad sobą, aby być gotowym na nowe relacje.",
      love_reverse:
        "W odwróconej pozycji, karta Wisielec oznacza często blokadę lub utknięcie w sytuacji, z której nie możemy się wydostać. W kontekście miłości, może to oznaczać, że mamy trudności w nawiązywaniu relacji lub w wyrażeniu swoich uczuć. Może to również wskazywać na trudności w zakończeniu toksycznej relacji lub w przejściu przez kryzys w związku.",
      Mistics:
        "Ukrzyżowany Chrystus. Izaak jako ofiara. Prometeusz związany. Jonasz i wieloryb. Łazarz. Każdy powieszony lub złożony w ofierze bóg. Judasz.",
      Questions_to_ask: [
        "Jak mogę radykalnie zmienić swoją perspektywę?",
        "Jak utknięcie może być błogosławieństwem w przebraniu?",
        "Jak mogę sobie pomóc, widząc szklankę do połowy pełną?",
      ],
    },
    {
      name: "Śmierć",
      number: "13",
      omen: "zły",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/smierc.jpg",
      fortune_telling: [
        "Związek lub choroba nagle się kończy",
        "Ogranicz podróżowanie i podejmowanie ryzyka",
        "Ogólny mrok i zagłada",
      ],
      keywords: ["kończący się", "wniosek", "przemiana", "przejście", "wyjazd"],
      meanings: {
        light: [
          "Zakończenie nieprzyjemnego etapu życia",
          "Rozpoznawanie i celebrowanie zakończenia czegoś",
          "Pozbądź się złych nawyków",
          "Stawanie się nową osobą",
          "Pozostawienie jednej osoby, miejsca lub rzeczy dla innej",
          "Odpuscic sobie",
        ],
        shadow: [
          "Obsesja na punkcie śmierci i umierania",
          "Odmowa porzucenia starych nawyków lub niezdrowych relacji",
          "Nalegając, aby wszystko i wszyscy pozostali tacy sami na zawsze",
          "Nie dbanie o siebie",
        ],
      },
      Archetype: "Śmierć",
      "Alfabet hebrajski": "Zakonnica/Ryba/50",
      Numerology: "13 = 1 + 3 = 4 (stabilność, wytrwałość)",
      Elemental: "Skorpion",
      love: "W pozycji prostej, Śmierć oznacza zwykle koniec jednego etapu życia, który prowadzi do nowych początków. W kontekście miłości może to oznaczać koniec jednej relacji i początek nowej. Oznacza to zwykle, że czasem trzeba przestać trwać w relacji, która nam nie służy, aby zacząć nowy związek, który będzie bardziej satysfakcjonujący i zdrowy. Ta karta może także odzwierciedlać pozytywne zmiany w naszym życiu miłosnym, takie jak otwarcie się na nowe doświadczenia i uczucia.",

      love_reverse:
        "W pozycji odwróconej, Śmierć może wskazywać na opór lub niechęć do zmiany. W miłości może to oznaczać, że osoba trzyma się przeszłości lub nie jest gotowa zakończyć trudnej relacji, mimo że wie, że powinna. Może to także sugerować, że osoba ma trudności z radzeniem sobie z przeszłością, co wpływa na jej obecne relacje. Ta karta może sugerować, że konieczne jest zakończenie trudnej relacji, aby osiągnąć zdrowie emocjonalne i zacząć nowy etap w życiu miłosnym.",
      Mistics:
        "Chrystus w grobie. Hades. Hypnos. Thanatos . Opowieści o podróżach do podziemi.",
      Questions_to_ask: [
        "Co musi się skończyć?",
        "Jak zakończenie może być błogosławieństwem w tej sytuacji?",
        "Co dalej?",
      ],
    },
    {
      name: "Umiarkowanie",
      number: "14",
      omen: "dobry",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/umiarkowanie.jpg",
      fortune_telling: [
        "Ktoś nadużywa narkotyków lub alkoholu",
        "Czas wrócić do tej diety",
      ],
      keywords: ["mieszanie", "synteza", "mediacja", "połączenie", "Harmonia"],
      meanings: {
        light: [
          "Łączenie przeciwieństw razem",
          "Moderowanie swoich działań lub emocji",
          "Znajdź złoty środek",
          "Osiąganie kompromisów",
          "Syntetyzowanie rozwiązań, które zadowolą wszystkich zaangażowanych",
          "Wykorzystanie starego do stworzenia czegoś nowego",
        ],
        shadow: [
          "Popadanie w skrajności",
          "Zakłócanie wysiłków grupowych",
          "Ignorowanie zdrowego podejścia do życia",
          "Stanie się uzależnionym",
          "Praktykowanie obżarstwa",
          "Rozdzieranie czegoś lub kogoś na strzępy",
          "Zerwanie sojuszy",
        ],
      },
      Archetype: "Mediator",
      "Alfabet hebrajski": " Samekh /Foundation/60",
      Numerology: "14 = 1 + 4 = 5 (katalizator, niestabilność, konfrontacja)",
      Elemental: "Strzelec",
      love: "Karta Umiarkowanie w pozycji prostej zazwyczaj sugeruje, że w twoim życiu miłosnym panuje spokój i równowaga. Oznacza to, że jesteś w stanie kontrolować swoje emocje i podejmować decyzje z umiarem, co prowadzi do zdrowych relacji. Może to również oznaczać, że jesteś w stanie zrozumieć swojego partnera i znaleźć kompromisy, dzięki czemu związek jest bardziej harmonijny.",
      love_reverse:
        "W pozycji odwróconej Umiarkowanie może wskazywać na problemy związane z brakiem równowagi i nadmiernym pochłonięciem emocji. Może to wskazywać na konflikty w związku, które wynikają z nadmiernej emocjonalności i braku umiaru. Zdarza się, że karta ta odwrócona może sugerować, że jedna ze stron związku dominuje nad drugą, co prowadzi do niezdrowych relacji.",
      Mistics:
        "Anioł tutaj widziany może być boginią Iris. Co za tym idzie, kapłani, kapłaństwo lub przemieniony Chrystus.",
      Questions_to_ask: [
        "Jak uniknąć skrajności?",
        "Co łączy wszystkich zaangażowanych ?",
        "Jak połączenie znanych rzeczy może pomóc mi stworzyć coś nowego?",
      ],
    },
    {
      name: "Diabeł",
      number: "15",
      omen: "zły",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/diabel.jpg",
      fortune_telling: [
        "Cudzołóstwo i niewierność",
        "Zbliża się pasmo skrajnego pecha",
        "Strzeżcie się złych wpływów i wilków w owczej skórze",
      ],
      keywords: ["cień", "materializm", "niewola", "złudzenie"],
      meanings: {
        light: [
          "Doceniając luksusy, jakie życie ma do zaoferowania",
          "Poczuć się dobrze we własnej skórze",
          "Cieszenie się swoją seksualnością",
          "Wydawanie pieniędzy na drogi przedmiot osobisty",
          "Przyjmując fakt, że każdy ma ciemną stronę",
          "Radzenie sobie z niezdrowymi impulsami w zdrowy sposób",
        ],
        shadow: [
          "Przywiązywanie nadmiernej wagi do wyglądu",
          "Zawsze chce więcej",
          "Docenianie własności bardziej niż ludzi lub relacji",
          "Pozwalając niskim instynktom rządzić twoim życiem",
          "Być samolubnym",
          "Przypisywanie własnych mrocznych impulsów siłom zewnętrznym lub innym ludziom",
        ],
      },
      Archetype: "Cień, inny",
      "Alfabet hebrajski": " Ayin /Oko/70",
      Numerology: "15 = 1 + 5 = 6 (dostosowanie, współpraca)",
      Elemental: "Koziorożec",
      love: "W pozycji prostej, karta Diabeł może oznaczać uzależnienie, pokusę, namiętność i pożądanie. Karta ta często sygnalizuje sytuacje, w których jedna osoba jest zniewolona przez drugą lub przez swoje własne słabości. Może to odnosić się do związku, w którym jedna strona dominuje nad drugą lub do sytuacji, w której jedna osoba jest uzależniona od drugiej emocjonalnie lub fizycznie. Karta ta może też wskazywać na potrzebę ucieczki od sytuacji, która nas przytłacza lub na konieczność podjęcia trudnych decyzji.",
      love_reverse:
        "W pozycji odwróconej, karta Diabeł wskazuje na wyzwolenie, uwolnienie się od okowów, uzdrowienie emocjonalne i wyjście z uzależnienia. Może to oznaczać przełamanie się z negatywnych nawyków, które wpływają na nasze relacje, lub uwolnienie się od osoby, która nas krzywdzi. Ta karta może być pozytywnym znakiem w kontekście związku, gdy jedna strona zdaje sobie sprawę z negatywnych wzorców, które wpływają na ich relację, i podejmuje kroki w celu ich przezwyciężenia.",
      Mistics:
        "Z pewnością biblijny szatan. Upadłe anioły, w tym Lucyfer. Bachus i Pan. Kusiciele i węże wszelkiego rodzaju.",
      Questions_to_ask: [
        "Co mnie zniewala? Jak mogę się uwolnić?",
        "Jak mogę ponownie ocenić wagę, jaką przywiązuję do rzeczy materialnych?",
        "W jakim stopniu definiują mnie moje zachcianki?",
      ],
    },
    {
      name: "Wieża",
      number: "16",
      omen: "zły",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/wieza.jpg",
      fortune_telling: [
        "Zbliżająca się katastrofa",
        "Anuluj plany i cofnij decyzje",
        "Ktoś chce cię sprowadzić o stopień lub dwa",
        "Nie powstrzymuj się, powiedz, co naprawdę masz na myśli",
      ],
      keywords: [
        "rozbiórka",
        "przewrót",
        "dekonstrukcja",
        "katastrofa",
        "zniszczenie",
      ],
      meanings: {
        light: [
          "Wyrwanie się ze starych, ograniczających nawyków i sposobów myślenia",
          "Otwarcie drogi dla nowego wzrostu",
          "Rozpraszanie wpływu rozdętego ego",
          "Powrót do podstaw",
          "Odzieranie szkodliwych złudzeń",
          "Otrzymanie nagłego wglądu",
        ],
        shadow: [
          "Trzymanie się tradycji, które hamują wzrost",
          "Angażowanie się w umyślną ślepotę",
          "Odrzucanie dowodów na to, że zmiana jest potrzebna",
          "Ignorowanie wskazówek siły wyższej",
          "Złośliwe angażowanie się w destrukcyjne zachowanie",
        ],
      },
      Archetype: "Roztrzaskane ego",
      "Alfabet hebrajski": " Pe [as]/otwarte usta/80",
      Numerology: "16 = 1 + 6 = 7 (psychologia, wyobraźnia, praca wewnętrzna)",
      Elemental: "Mars",
      love: "Wieża może oznaczać, że związek znajduje się w kryzysie i zmierza ku upadkowi. Może to być wynikiem niespodziewanych wydarzeń lub trudnych decyzji, które zostaną podjęte. W pozytywnej interpretacji, karta ta może oznaczać konieczność zmiany i wzniesienia się na wyższy poziom w związku. Często to, co wydaje się być negatywne na pierwszy rzut oka, jest w rzeczywistości potrzebną lekcją dla rozwoju związku.",
      love_reverse:
        "Jeśli chodzi o interpretację odwróconej karty Wieża, może to oznaczać, że napięcia i problemy emocjonalne w związku zaczynają ustępować, a związek zaczyna się stabilizować. Oznacza to, że kryzys został zażegnany i teraz jest czas na odbudowanie związku na nowych podstawach.",
      Mistics:
        "Wieża Babel. Zniszczenie Sodomy i Gomory. Niszczycielski taniec Shivy. Błyskawica Zeusa i Thora.",
      Questions_to_ask: [
        "W jaki sposób obecna sytuacja może radykalnie zmienić moją perspektywę?",
        "Jak ta strata może otworzyć drzwi do nowego rozwoju?",
        "Jakie postawy należy obalić, zanim podejmę dalsze działania?",
      ],
    },
    {
      name: "Gwiazda",
      number: "17",
      omen: "dobry",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/gwiazdy.jpg",
      fortune_telling: [
        "Poproś o sporządzenie wykresu astrologicznego",
        "Ktoś jest trochę zbyt oszołomiony ",
        "To, co się teraz dzieje, zostało z góry ustalone",
      ],
      keywords: [
        "nadzieja",
        "optymizm",
        "otwartość",
        "pewność",
        "wiara",
        "tęsknota",
        "prawda",
      ],
      meanings: {
        light: [
          "Mam nadzieję na najlepsze",
          "Wiara, że dobre rzeczy przydarzają się dobrym ludziom",
          "Postrzeganie wydarzeń w jak najlepszym świetle",
          "Przyjęcie wielkodusznego ducha",
          "Szukając przewodnictwa z góry",
          "Przedkładanie możliwości nad prawdopodobieństwem",
        ],
        shadow: [
          "Zaprzeczanie przykrym prawdom",
          "Zaprzeczanie osobistej odpowiedzialności i mówienie: tak się po prostu zdarza",
          "Ignorowanie znaków i znaków",
          "Preferując iluzję od rzeczywistości",
          "Szerzenie pesymizmu i skąpstwa ducha",
        ],
      },
      Archetype: "Niebiański przewodnik",
      "Alfabet hebrajski":
        " Tzaddi /Fishhook/90 lub, w niektórych taliach, On [as]/Okno/5",
      Numerology: "17 = 1 + 7 = 8 (akcja, ruch, szybkość)",
      Elemental: "Wodnik",
      love: "W pozycji prostej, karta Gwiazda symbolizuje poczucie spokoju i ukojenia. Może to oznaczać, że relacja jest stabilna i harmonijna, a uczucia są silne i pełne nadziei na przyszłość. Oznacza to także, że obie strony w związku są gotowe na poświęcenie i oparcie, gdy tylko jest to potrzebne. Co do pytania o uczucia drugiej osoby, to karta wskazuje na uczucia szczere i otwarte. W pozycji prostej może to oznaczać, że druga osoba jest gotowa na szczere rozmowy.",
      love_reverse:
        " W pozycji odwróconej, karta Gwiazda może sugerować, że nadzieje i pragnienia są przesadnie wysokie lub nierealistyczne, co może prowadzić do rozczarowania. Może to również wskazywać na trudności w komunikacji i brak pewności siebie w relacji, co prowadzi do napięcia i braku harmonii. Może to wskazywać na brak pewności siebie, napięcia i problemy z otwartą komunikacją.",
      Mistics:
        "Gwiazda, która prowadziła Mędrców. Afrodyta. Wenus. Plejady. Mojżesz wydobywający wodę ze skały.",
      Questions_to_ask: [
        "Co poleciłaby mi moja siła wyższa ?",
        "Jak mogę być mniej skrępowany i ostrożny?",
        "Jak mogę lepiej dostroić się do obfitości błogosławieństw życia?",
      ],
    },
    {
      name: "Księżyc",
      number: "18",
      omen: "dobry",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/ksiezyc.jpg",
      fortune_telling: [
        "Uważaj na problemy pod koniec miesiąca",
        "Ktoś, kogo znasz, musi zwrócić większą uwagę na księżyc",
        "Ktoś ma zamiar zmienić zdanie w sprawie ważnej decyzji",
      ],
      keywords: [
        "tajemnica",
        "Fantazja",
        "wyobraźnia",
        "marzenia",
        "niepewność",
      ],
      meanings: {
        light: [
          "Cieszenie się zdrowymi fantazjami i marzeniami",
          "Korzystajanie z wyobraźni",
          "Praktykowanie magii lub celebrowanie magii codzienności",
          "Dostrajanie się do cykli natury",
          "Obejmując nieznane",
        ],
        shadow: [
          "Niemożność oddzielenia fantazji od rzeczywistości",
          "Cierpienie na urojenia",
          "Utrata uznania dla tego, co fantastyczne lub magiczne",
          "Przyjęcie bezwzględnie logicznego sposobu myślenia",
          "Nie docenić tajemnic życia",
        ],
      },
      Archetype: "Święta kobiecość / Starucha",
      "Alfabet hebrajski": " Koph /tył głowy/100",
      Numerology: "18 = 1 + 8 = 9 (pełnia, gotowość, dojrzałość)",
      Elemental: "Ryby",
      love: "W pozycji prostej, karta Księżyc może oznaczać, że miłość i uczucia są niejasne, skomplikowane i wymagają głębszej analizy i zrozumienia. Może to oznaczać, że musimy uważnie obserwować nasze emocje i intuicję, aby móc zrozumieć, co czujemy i jakie są nasze potrzeby w związku.Co do uczuć drugiej osoby do nas, karta Księżyc może wskazywać na to, że druga osoba jest niezdecydowana i ma mieszane uczucia wobec nas.",

      love_reverse:
        "  W pozycji odwróconej, karta Księżyc może wskazywać na zakłamanie lub brak szczerości w relacji między partnerami. Może to oznaczać, że jedna z osób ukrywa przed drugą swoje prawdziwe uczucia lub że coś jest nie tak w naszym związku. Ta karta może być ostrzeżeniem przed manipulacją lub oszustwem. Co do uczuć drugiej osoby do nas -  karta ta może wskazywać na to, że ta osoba ukrywa przed nami pewne fakty lub uczucia, co może prowadzić do nieporozumień",
      Mistics:
        "Kali, ciemnoskóra boska matka związana z czasem, wieczną nocą i kobiecą zasadą. Hekate, bogini nocy i ciemności, która podobnie jak Anubis pomaga innym w ich podróżach do podziemi. ",
      Questions_to_ask: [
        "Jak mogę stawić czoła moim lękom i iść naprzód?",
        "Którzy pomocnicy mogą mi służyć jako przewodnicy przez moją osobistą ciemność?",
        "Jak mogę radzić sobie z nieznanym w zdrowy sposób?",
      ],
    },
    {
      name: "Słońce",
      omen: "dobry",
      number: "19",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/slonce.jpg",
      fortune_telling: [
        "Wszystko zbliża się do róż (lub słoneczników, cokolwiek by to nie było)",
        "Cokolwiek masz na myśli, zrób to, bo nie możesz dziś przegrać",
      ],
      keywords: ["radość", "blask", "walidacja", "Uwaga", "energia"],
      meanings: {
        light: [
          "Widzenie rzeczy jasno",
          "Doświadczanie intensywnej radości",
          "Świętowanie własnych sukcesów",
          "Wiedząc, że jesteś dobry w tym, co robisz",
          "Zdobądź uznanie za swój osobisty geniusz",
        ],
        shadow: [
          "Być olśnionym własnymi osiągnięciami",
          "Zaabsorbowanie się własnym obrazem siebie",
          "Poczucie pośpiechu i rozproszenia",
          "Wytężanie sił aż do wyczerpania",
          "Przecenianie swoich umiejętności lub fałszywe przedstawianie osiągnięć",
        ],
      },
      Archetype: "Święta męskość",
      "Alfabet hebrajski": " Resh /Head/200",
      Numerology:
        "19 = 1 + 9 = 10 (ukończenie, wyczerpanie) 1 + 0 = 1 (punkt wyjścia, okazja)",
      Elemental: "Słońce",
      love: "W pozycji prostej, karta Słońce może wskazywać na rozwój relacji między dwoma osobami, które cieszą się sobą nawzajem i mają dobre perspektywy na przyszłość. Karta ta może oznaczać miłość, która jest szczera, witalna i pełna radości. Jeśli jesteś w związku, karta  może wskazywać na stabilność i szczęście, które przynosi ta relacja. Jeśli szukasz miłości, karta może wskazywać na pozytywne i radosne doświadczenia miłosne. Może wskazywać na szczere i otwarte uczucia ze strony drugiej osoby.",
      love_reverse:
        " W pozycji odwróconej, karta Słońce może wskazywać na problemy z komunikacją w związku lub brak zaufania między partnerami. Karta ta może też oznaczać trudne wybory i dylematy w kwestiach miłosnych. Jednakże, zwykle interpretacja tej karty w pozycji odwróconej jest bardziej złożona i zależy od kontekstu.",
      Mistics:
        "Bóg Ojciec. Bogowie słońca, w tym Ra, Apollo i Helios. Moment chrztu. Uznanie nowej wiary za własną.",
      Questions_to_ask: [
        "Jak najlepiej wykorzystać uwagę, która mnie otacza ?",
        "Jakie są moje najwyższe cele duchowe?",
        "Jak mogę uniknąć olśnienia energią wirującą wokół mnie?",
      ],
    },
    {
      name: " Sąd ostateczny ",
      number: "20",
      omen: " zły",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/sad-ostateczny.jpg",
      fortune_telling: [
        "Stary problem, o którym myślałeś, że się skończył, dzisiaj wróci",
        "Przygotuj się na ogromne zmiany: rozstania, nagłe telefony od starych przyjaciół i nieoczekiwane niepowodzenia",
        "Bóg próbuje zwrócić twoją uwagę",
      ],
      keywords: [
        "odrodzenie",
        "odnowienie",
        "zmartwychwstanie",
        "ocena",
        "zaproszenie",
      ],
      meanings: {
        light: [
          "Odbiór budzenia",
          "Odkrywanie nowego celu w życiu",
          "Stanie się całkowicie i całkowicie sobą",
          "Otrzymanie zasłużonej nagrody",
          "zdanie oceny lub egzaminu",
          "Witamy początek nowego etapu życia",
        ],
        shadow: [
          "Zważony na wadze i znaleziony lekkim",
          "Nie można zmierzyć się z dobrze zdefiniowanym standardem",
          "Przyłapanie na wygłupianiu się lub niewłaściwym zachowaniu",
          "Nieprzygotowanie się do egzaminu, o którym wiesz, że się zbliża",
          "Odrzucanie okazji do wymyślenia siebie na nowo",
        ],
      },
      Archetype: "Zmartwychwstanie",
      "Alfabet hebrajski": "Grzech/Ząb/300",
      Numerology: "20 = 2 + 0 = 2 (podział, dwoistość)",
      Elemental: "Ogień",
      love: "W pozycji prostej, ta karta może wskazywać na to, że jesteśmy gotowi do podjęcia decyzji, która zmieni nasze życie. Może to być decyzja o zakończeniu związku lub ostatecznym zobowiązaniu wobec partnera. Co więcej, karta ta może także wskazywać na potrzebę przebaczenia i wybaczania, zarówno dla siebie jak i dla innych",
      love_reverse:
        "W pozycji odwróconej karta Sąd Ostateczny może sugerować, że trudno nam podjąć decyzję lub boimy się jej podjąć. Może to oznaczać, że wciąż trzymamy się pewnych przeszłościowych wzorców lub sytuacji, które blokują naszą zdolność do podjęcia kroku naprzód.",
      Mistics:
        "Zmartwychwstały Chrystus. Sąd Ostateczny według Objawienia. Feniks, który odradza się do nowego życia z własnych popiołów.",
      Questions_to_ask: [
        "Co jest najważniejsze, co muszę sobie uświadomić ?",
        "W jaki sposób wszechświat może próbować zwrócić moją uwagę?",
        "Gdybym miał wymyślić siebie na nowo, kim bym się stał ?",
      ],
    },
    {
      name: "Świat",
      omen: "dobry",
      number: "21",
      arcana: "Wielka Arkana",
      suit: "Trump",
      img: "https://www.myslczlowieku.pl/wp-content/uploads/2022/12/swiat.jpg",
      fortune_telling: [
        "Wygrana na loterii",
        "Spełnianie pragnień serca",
        "Zdobycie wszystkiego o czym kiedykolwiek marzyliśmy",
      ],
      keywords: ["całość", "integracja", "całość", "kompletność", "pełnia"],
      meanings: {
        light: [
          "Mieć wszystko",
          "Poznać i pokochać siebie tak dokładnie, jak to możliwe",
          "Widząc wzajemne połączenie wszystkich rzeczy i ludzi",
          "Wzbogacanie swojej perspektywy",
          "Żyj pełnią życia",
          "Zrozumieć sens życia",
        ],
        shadow: [
          "Pozwalając, by chciwość i zazdrość uniemożliwiły ci cieszenie się tym, co posiadasz",
          "Nie dostrzeganie większego projektu w zwykłych wydarzeniach",
          "Wiara, że wszystko, co istnieje, można dotknąć, policzyć lub zmierzyć",
          "Nie dostrzeganie boskości odzwierciedlonej w otaczających cię ludziach",
        ],
      },
      Archetype: "Oświecenie",
      Numerology: "21 = 2 + 1 = 3 (wyrażenie, wynik)",
      Elemental: "Saturn",
      love: "Karta Świat w pozycji prostej może oznaczać, że znajdujemy się w fazie spełnienia naszych pragnień w związku lub znajdujemy się w fazie, w której nasza miłość rozkwita i rozwija się. Wskazuje na to, że relacja ta jest wspaniała, pełna harmonii i zgodna z naszymi pragnieniami. W tej pozycji karta ta może również symbolizować zakończenie trudnego okresu w naszej miłości, w którym musieliśmy zmierzyć się z trudnościami, ale w końcu udało nam się przetrwać i osiągnąć porozumienie",
      love_reverse:
        "Karta Świat w pozycji odwróconej może oznaczać, że czujemy się zagubieni i niezdecydowani w naszym związku lub w ogóle w kwestii miłości. Może to oznaczać, że potrzebujemy czasu, aby znaleźć swoje miejsce w życiu miłosnym lub że nasze relacje są w nieustannym rozdźwięku. W tej pozycji karta ta może także oznaczać, że nadmiernie polegamy na innych w naszych związkach i potrzebujemy nauczyć się być bardziej niezależnymi.",
      Mistics:
        "Wniebowstąpiony Chrystus. Budda osiągający oświecenie. Alfa i omega. Zakończenie wielkiego dzieła alchemika.",
      Questions_to_ask: [
        "Co oznaczałoby dla mnie posiadanie tego wszystkiego ?",
        "Jak jestem świadomy mojego własnego związku z otaczającym mnie światem?",
        "Co powstrzymuje mnie przed posiadaniem tego wszystkiego teraz, dzisiaj? ",
      ],
    },
  ],
};
